name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish-to-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
    - name: Build
      working-directory: ./src/Client
      run: dotnet build -c Release -p:Version=${GITHUB_REF#refs/tags/v}
    - name: Get the nuget signing certificate
      id: cert_file
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'certfile.pfx'
        encodedString: ${{ secrets.NUGET_CERTIFICATE }}
    - name: Sign the nuget package
      working-directory: ./src/Client
      run: dotnet nuget sign ./bin/Release/Pieces.OS.Client.${GITHUB_REF#refs/tags/v}.nupkg --certificate-path /tmp/certfile.pfx --certificate-password ${{ secrets.NUGET_CERTIFICATE_PASSWORD }} --timestamper http://timestamp.digicert.com
    - name: Push to NuGet
      working-directory: ./src/Client
      run: dotnet nuget push ./bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.org

    